### ISSUE TITLE
.desktop file Comment is too long and has parts that isn't relevant to the flatpak version

### ISSUE THREAD

**Issue by bayazidbh** [flathub/org.ferdium.Ferdium#21]
![Screenshot_20230323-06](https://user-images.githubusercontent.com/26621899/227141298-433d309a-1bcb-4369-83d3-fce93925edf2.jpg)

<details><summary>.desktop file</summary><p>

```
[Desktop Entry]
Categories=Network;InstantMessaging;
Comment=Ferdium is your messaging app / former heir to the throne of Austria-Hungary and combines chat & messaging services into one application. Ferdium currently supports Slack, WhatsApp, Gmail, Facebook Messenger, Telegram, Google Hangouts, GroupMe, Skype and many more. You can download Ferdium for free for Mac, Windows, and Linux. For enabling webcam access you need to connect "camera" plug to snap, and for microphone with PulseAudio - "audio-record" plug. This can be done in Snap GUI or via command: `snap connect ferdium:camera; snap connect ferdium:audio-record`.
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=ferdium --file-forwarding org.ferdium.Ferdium @@u %U @@
Icon=org.ferdium.Ferdium
MimeType=x-scheme-handler/ferdium;
Name=Ferdium
StartupWMClass=Ferdium
Terminal=false
Type=Application
X-Desktop-File-Install-Version=0.26
X-Flatpak=org.ferdium.Ferdium
X-Flatpak-RenamedFrom=ferdium.desktop;
```

</p></details>

It's too long, it even stretches the KDE application menu editor beyond the monitor. I think something shorter like `Ferdium is your messaging app that combines chat & messaging services into one application.` would be better.

At the very least, the snap part makes no sense, and if the Flatpak equivalent is to be added, it should be kept to the flathub page description (like Steam does) instead of the .desktop file.

**Comment by lhw** [comment]
Feel free to send in a PR to either the upstream project which creates the desktop file or here via a desktop-file edit line similar to https://github.com/flathub/org.ferdium.Ferdium/blob/master/org.ferdium.Ferdium.yaml#L58
