### ISSUE TITLE
Verify Flatpak ownership

### ISSUE THREAD

**Issue by deadmeu** [flathub/org.ferdium.Ferdium#23]
The beta Flathub site has a feature to [verify the ownership](https://beta.flathub.org/about) of Flatpaks. This lets users feel more confident that they are downloading an official and safe release. It would be great if Ferdium was recognised as a verified release on the website.

**Comment by skipperTux** [comment]
Shall this issue be cross-linked to the [ferdium-app issues](https://github.com/ferdium/ferdium-app/issues), so someone from the Ferdium lead contributors can support the verification process?

**Comment by lhw** [comment]
Done
