### ISSUE TITLE
Version on flathub is outdated - 6.2.6 should be 6.2.7

### ISSUE THREAD

**Issue by matthewdavis** [flathub/org.ferdium.Ferdium#26]
```
mdavis@matt-desktop: ~ $ flatpak update org.ferdium.Ferdium
Looking for updates…

Nothing to do.
mdavis@matt-desktop: ~ $ flatpak info org.ferdium.Ferdium

Ferdium - Messenger for the desktop

          ID: org.ferdium.Ferdium
         Ref: app/org.ferdium.Ferdium/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 6.2.6
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 372.3 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 1180b21272f058aa05b091f32db5cf4c94c29d367c97cfa3f50f752804eabf65
      Parent: 9fc6c9371bdce94b2d34893d830258b5409131472930c5519ef20d9ee35f52b8
     Subject: Update 3 modules (d38a0176)
        Date: 2023-04-01 22:24:41 +0000
mdavis@matt-desktop: ~ $ grep Url /etc/flatpak/remotes.d/flathub.flatpakrepo 
3:Url=https://dl.flathub.org/repo/
mdavis@matt-desktop: ~ $ 
```

And if I goto https://flathub.org/apps/org.ferdium.Ferdium the version is still 6.2.6. Not sure what needs to happen because I know this [commit](https://github.com/flathub/org.ferdium.Ferdium/commit/cf8c1e66084651197e56deb42eecd23f5788b308) was made.

**Comment by digrouz** [comment]
Even further, i see that 6.2.8 and 6.3.0 were released even. What needs to be done to make flathub reflect thoses upgrades ?

**Comment by xalt7x** [comment]
There's a [pull request for 6.3.0](https://github.com/flathub/org.ferdium.Ferdium/pull/27) with an instruction how to obtain test  build.
Not sure why 6.2.7 and 6.3.0 weren't not published on Flathub yet.

**Comment by digrouz** [comment]
The command is not working, it returns 404

**Comment by hfiguiere** [comment]
6.2.7 failed to build. But with #28 it should be published soon.

**Comment by hfiguiere** [comment]
> The command is not working, it returns 404

builds do expire.
